version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - adminer
      - redis
      - hugo
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb
    env_file: .env
    expose:
      - 3306
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    env_file:
      - .env

  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    container_name: wordpress
    env_file: .env
    expose:
      - 9000
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/html

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/jannabel/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/jannabel/data/wordpress
      o: bind

networks:
  network:
    driver: bridge